In [0]:
import pickle, gzip
import numpy as np

# Loading the data

In [3]:
## load data
 
f = gzip.open('/mnist_10000.pkl.gz', 'rb')
trainData, trainLabels, valData, valLabels, testData, testLabels = pickle.load(
    f, encoding='latin1')
f.close()
 
print("training data points: {}".format(len(trainLabels)))
print("validation data points: {}".format(len(valLabels)))
print("testing data points: {}".format(len(testLabels)))

training data points: 10000
validation data points: 2000
testing data points: 2000


# Task 1

Try the following values of K, and note the classification accuracy on the validation data for each. K = 1, 3, 5, 9, 15, 25

In [0]:
from sklearn.neighbors import KNeighborsClassifier

In [5]:
## train model
 
for k in [1, 3, 5, 9, 15, 25, ]:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(trainData, trainLabels)
    # KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
    #            metric_params=None, n_jobs=1, n_neighbors=5, p=2,
    #            weights='uniform')
 
    score = model.score(valData, valLabels)
    print(k, score) 

1 0.947
3 0.953
5 0.948
9 0.9405
15 0.9335
25 0.9235


#Task 2

For the best performing value of K, calculate and note the classification accuracy on the test data. 

In [6]:
# re-train our classifier using the best k value and predict the labels of the
# test data

best_k = 25
model = KNeighborsClassifier(n_neighbors=best_k)
model.fit(trainData, trainLabels)
accuracy = model.score(testData, testLabels)
print("Achieved accuracy of %.2f%% on test data" % (accuracy*100))

Achieved accuracy of 89.80% on test data


#Task 3
Inspect the performance per class, i.e. precision, recall and f-score for each digit. 

In [7]:
from sklearn.metrics import classification_report

# show a final classification report demonstrating the accuracy of the classifier
# for each of the digits
predictions = model.predict(testData)
print("Classification Report")
print(classification_report(testLabels, predictions))

Classification Report
              precision    recall  f1-score   support

           0       0.92      0.99      0.95       175
           1       0.79      1.00      0.88       234
           2       0.99      0.77      0.87       219
           3       0.91      0.91      0.91       207
           4       0.94      0.88      0.91       217
           5       0.96      0.88      0.92       179
           6       0.91      0.96      0.94       178
           7       0.87      0.88      0.87       205
           8       0.97      0.78      0.86       192
           9       0.83      0.94      0.88       194

    accuracy                           0.90      2000
   macro avg       0.91      0.90      0.90      2000
weighted avg       0.91      0.90      0.90      2000



#Task 4
Inspect the confusion matrix, i.e. when the correct label was digit I, how times did the model predict J.

In [8]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix")
print(confusion_matrix(testLabels, predictions))

Confusion Matrix
[[174   0   0   0   0   0   1   0   0   0]
 [  0 234   0   0   0   0   0   0   0   0]
 [  6  24 169   0   1   0   4  11   4   0]
 [  0   4   0 189   0   1   2   7   1   3]
 [  0   5   0   0 191   0   4   2   0  15]
 [  2   3   0   6   1 157   3   2   0   5]
 [  3   1   0   0   2   1 171   0   0   0]
 [  0  19   0   0   1   0   0 180   0   5]
 [  3   6   2   9   5   4   2   3 149   9]
 [  2   2   0   3   2   0   0   3   0 182]]
